services:
  - type: web
    name: workshift-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432